baseURL = "https://jamesagibson.com/"
languageCode = "en-us"
sectionPagesMenu = "main"
title = "James A. Gibson" 
theme = "hermit"


[author]
    name = "James A. Gibson"

[deployment]
  [[deployment.targets]]
    name = "production"
    URL = "s3://jamesagibson.com?region=us-west-2"

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04 -0700"
    footerCopyright = "All Rights Reserved"
    homeSubtitle    = "My Home in the Cloud"

  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/jamesalangibson"

  [[params.social]]
    name = "email"
    url = "mailto:jamesagibson@protonmail.com"