baseURL           = "https://jamesagibson.com/"
languageCode      = "en-us"
sectionPagesMenu  = "main"
title             = "James A. Gibson" 
theme             = "hermit"
googleAnalytics   = "UA-82311924-1"


[author]
    name = "James A. Gibson"

[deployment]
  [[deployment.targets]]
    name    = "production"
    URL     = "s3://jamesagibson.com?region=us-west-2"
    cloudFrontDistributionID = "EBLH61CC4CPPK"

[params]
  customCSS       = ["css/custom.css"]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04 -0700"
  footerCopyright = "All Rights Reserved"
  homeSubtitle    = "My Home in the Cloud"
  gtm             = "GTM-MFB7C9L"


  # Social Icons
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/jamesalangibson"
  
  [[params.social]]
    name = "github"
    url = "https://github.com/jamesalangibson"

  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/james-a-gibson"

  [[params.social]]
    name = "email"
    url = "mailto:jamesagibson@protonmail.com"